# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
gem: [jekyll-paginate, jekyll-gists]

# Setup
title:            mcilloni's blog
tagline:          'A simple blog for rather complicated topics'
description:      'A collection of rants, experiments and experiences collected during my decade-long delve into the magical world of computers.'
url:              https://www.mcilloni.ovh
baseurl:          /

author:
  name:           'Marco Cilloni'
  url:            https://twitter.com/mcilloni

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mcilloni/mcilloni.github.io
