# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
gem: [jekyll-paginate, jekyll-gists]

# Setup
title:            mcilloni's blog
tagline:          'A simple blog for rather complicated topics'
description:      'Rants, experiments and experiences collected while delving into the magical world of computers.'
url:              https://mcilloni.ovh
baseurl:          /

author:
  name:           'Marco Cilloni'
  email:          'cillonimarco@gmail.com'
  twitter:        'mcilloni'
  github:         'mcilloni'
  linkedin:       'mcilloni'

paginate:         5

# Custom vars
version:          2.1.0
disqus:		  true
